export const GET_IMAGE_REQUEST = "GET_IMAGE_REQUEST"
export const GET_IMAGE_SUCCESS = "GET_IMAGE_SUCCESS"
export const GET_IMAGE_FAILURE = "GET_IMAGE_FAILURE"


export const GET_SPECIFIC_IMAGE_REQUEST = "GET_SPECIFIC_IMAGE_REQUEST"
export const GET_SPECIFIC_IMAGE_SUCCESS = "GET_SPECIFIC_IMAGE_SUCCESS"
export const GET_SPECIFIC_IMAGE_FAILURE = "GET_SPECIFIC_IMAGE_FAILURE"